version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    networks:
      - default

  redis:
    image: redis:latest
    command: redis-server --requirepass febriano
    ports:
      - "6379:6379"
    networks:
      - default

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./database/data:/var/lib/postgresql/data
#      - ./database/product.sql:/docker-entrypoint-initdb.d/product.sql

networks:
  default:
